### PR TITLE
assets/nora: Add info to Readme

### PR DESCRIPTION
**Pull request by arjun024**
Info for bosh windows stemcell users

### Are you submitting this PR against the [develop branch](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop)?

_All PR's to CATs should be submitted to develop and will be merged to master once they've passed acceptance._

### What is this change about?

Trivial readme change

### Please provide contextual information.

_Include any links to other PRs, stories, slack discussions, etc... that will help establish context._

### Please check all that apply for this PR:
- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [ ] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?
- [X] YES
- [ ] N/A

### If you are introducing a new acceptance test, what is your rationale for including it CATs rather than your own acceptance test suite?

_CATs should validate common operator workflows._
_CATs is not a regression test suite._
_CATs is run by every component team to validate their releases before promotion._

### How should this change be described in cf-acceptance-tests release notes?

_Something brief that conveys the change and is written with the component author audience in mind._

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

### CODE REVIEW

**Comment by weymanf** [comment]
Hello Arjun. Just a heads up for you to finish up the CLA authorization so we can merge this in.

**Comment by arjun024** [comment]
@weymanf Hey Weyman, I have signed the CLA. I just happened to author the commit using the wrong email but I corrected it. It doesn't look like the CLA bot is rerunning the test after my force push!

**Comment by weymanf** [comment]
@arjun024 We tried closing and reopening doesn't seem to retrigger. Could you try pushing pushing an empty commit?

**Comment by arjun024** [comment]
@weymanf Done

**Pull request merged**
