### PR TITLE
fix: faulty test logic

### PR DESCRIPTION
**Pull request by swalchemist**
* Avoids possible false pass

Co-Authored-By: Bruce Ricard <bricard@vmware.com>

### What is this change about?

Fixes what appears to be a typo in the logic that makes the test less effective than intended.

### Please check all that apply for this PR:
- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [x] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?
- [ ] YES
- [x] N/A

### If you are introducing a new acceptance test, what is your rationale for including it CATs rather than your own acceptance test suite?

_CATs should validate common operator workflows._
_CATs is not a regression test suite._
_CATs is run by every component team to validate their releases before promotion._

### How should this change be described in cf-acceptance-tests release notes?

Fixes what appears to be a typo in the logic that makes the test less effective than intended.

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

None.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
@bruce-ricard

### CODE REVIEW

**Comment by jochenehret** [comment]
@swalchemist : Do you need assistance with the CLA?

**Review by davewalter — APPROVED** [review]

**Comment by davewalter** [comment]
@swalchemist Try closing it and re-opening it again. If that doesn't work, I would create a new PR from the branch.

**Comment by davewalter** [comment]
I'm going to try closing and reopening this PR to see if that helps.

**Review by davewalter — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
