### PR TITLE
Re-enable .NET core buildpack test

### LINKED ISSUE #544: .NET Core Test Pended for 6 Years
I was on the hunt for a sample .NET Core sample app and noticed that the [dotnet-core](https://github.com/cloudfoundry/cf-acceptance-tests/tree/8f5ccaf914f94c9aac9113317b4d69060e19c934/assets/dotnet-core) app in assets does not work on modern Cloud Foundry.

Investigating how this was possible, I discovered that the .NET core test using that app has been pended since 2016
https://github.com/cloudfoundry/cf-acceptance-tests/blob/8f5ccaf914f94c9aac9113317b4d69060e19c934/detect/buildpacks.go#L118-L129

Commit that pended it: https://github.com/cloudfoundry/cf-acceptance-tests/commit/24854e1dc2764003d48b89b2df61afd2317958d2

We should fix and unpend the test or, failing that, delete it.

### PR DESCRIPTION
**Pull request by Gerg**
### Are you submitting this PR against the [develop branch](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop)?

Yes

### What is this change about?

Re-enable .NET core buildpack test

### Please provide contextual information.

- This test was previously pended in 24854e1.
- In the meanwhile, the sample application's .NET version drifted out of
  what is supported by the .NET Core buildpack.
- The sample application did not include source code, so it was
  impossible to update to new .NET versions.
- This replaces the sample application with one borrowed from the
  dotnet-core-buildpack's test fixtures. This is a source application,
  so it will be easier to update in the future (but maybe slower).
- Hopefully time and/or the new sample app will address the reasons the
  test was originally pended 🤞.

Fixes #544

### What version of cf-deployment have you run this cf-acceptance-test change against?

v21.0.0

### Please check all that apply for this PR:

- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [x] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?

- [ ] YES
- [x] N/A

### If you are introducing a new acceptance test, what is your rationale for including it CATs rather than your own acceptance test suite?

N/A

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

```
Running Suite: CATS
===================
Random Seed: 1654292200
Will run 228 specs

Running in parallel across 4 nodes

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
Running CATs with CF CLI version  cf version 8.0.0+b04b29dab.2022-05-12



• [SLOW TEST:97.080 seconds]
[detect]
/Users/gcobb/go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:87
  Buildpacks
  /Users/gcobb/go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:93
    dotnet-core
    /Users/gcobb/go/src/github.com/cloudfoundry/cf-acceptance-tests/detect/buildpacks.go:118
      makes the app reachable via its bound route
      /Users/gcobb/go/src/github.com/cloudfoundry/cf-acceptance-tests/detect/buildpacks.go:119
------------------------------

Ran 1 of 228 Specs in 152.709 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 227 Skipped
```

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

@dsabeti

### CODE REVIEW

**Comment by ctlong** [comment]
The unit tests failure appears to be due to `cf-test-helpers`, which were just bumped to ginkgo v2. Need to block this PR on #543.

**Comment by davewalter** [comment]
@Gerg @ctlong Does this PR branch need to be rebased to pick up the Ginkgo v2 work?

**Comment by ctlong** [comment]
Rebased.

**Comment by ctlong** [comment]
@Gerg are there any dependencies for the dotnet-core app that would cause us to want to write it into this repo's [dependabot config](https://github.com/cloudfoundry/cf-acceptance-tests/blob/develop/.github/dependabot.yml)? What [dependency manager](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) does the app use?

**Comment by Gerg** [comment]
I don't think the app has any external dependencies other than the dotnet runtime, which comes from the dotnet core buildpack.

**Comment by moleske** [comment]
for future reference, if dependencies are added that aren't the dotnet runtime, they would be in the csproj file.  The dependabot setting that would be used for updating would be nuget

**Pull request merged**
