### PR TITLE
v3 helpers retrieves doppler endpoint from v2/info

### PR DESCRIPTION
**Pull request by keymon**
The v3 helper has building the doppler URL in a hardcoded way. It does
not include the protocol, so it assumes HTTP, does not add the port and
assumes that the name is s/api/doppler/

In this commit we query the /v2/info endpoint to extract the doppler
endpoint. We replace the websocket protocol (ws) with HTTP (http). If
it is a SSL Websocket (wss) the string replacement will result in https.

In our specific case, we only serve HTTPS for doppler, so the test fails due timeout.

### CODE REVIEW

**Comment by dsabeti** [comment]
Hey @keymon. Could you explain a little more why you need to replace the Websocket protocol with `http`?

Also, I'll ask @zrob and @Gerg to take a look at this PR. They're have more experience with the `v3` test suite.

**Comment by keymon** [comment]
The original test shells out to call curl, and curl uses http, no websocket. In the original code you do not specify the protocol, so implicitly uses http

**Comment by dsabeti** [comment]
I see, @keymon. You're just replicating the existing behavior.

@zrob Should I prioritize this in the RelInt backlog, or would you rather have CAPI look at it?

**Comment by ScarletTanager** [comment]
@ericpromislow and I ran CATS on this, we're merging this PR.

**Pull request closed without merging**
