### PR TITLE
Fix default variables test only getting recent logs once

### LINKED ISSUE #218: Timing issue on Environment Variables Task test
We recently started having a consistently failing test, which looks to be somewhat new:
```
• Failure [35.633 seconds]
[apps] Default Environment Variables
/go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:38
  Default staging environment variables
  /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/default_environment_variables.go:179
    applies default environment variables while running apps and tasks [It]
    /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/default_environment_variables.go:178

    Expected
        <string>: Connected, dumping recent logs for app CATS-2-APP-11a34b0f-988a-400c-6 in org CATS-2-ORG-c5422bbe-f07a-4ba1-5 / space CATS-2-SPACE-ab57098b-8701-4859-5 as CATS-USER-2-2017_06_27-15h35m04.78s...
        
        2017-06-27T16:38:27.35+0000 [API/0]      OUT Created app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
        2017-06-27T16:38:27.77+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"route"=>"583b3a7a-1942-4944-914b-fade1316bded", :verb=>"add", :relation=>"routes", :related_guid=>"583b3a7a-1942-4944-914b-fade1316bded"})
        2017-06-27T16:38:33.89+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"diego"=>true})
        2017-06-27T16:38:34.58+0000 [API/0]      OUT Creating build for app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
        2017-06-27T16:38:34.70+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"state"=>"STARTED"})
        2017-06-27T16:38:34.73+0000 [STG/0]      OUT Downloading binary_buildpack...
        2017-06-27T16:38:34.74+0000 [STG/0]      OUT Downloaded binary_buildpack
        2017-06-27T16:38:34.74+0000 [STG/0]      OUT Creating container
        2017-06-27T16:38:35.34+0000 [STG/0]      OUT Successfully created container
        2017-06-27T16:38:35.34+0000 [STG/0]      OUT Downloading app package...
        2017-06-27T16:38:35.38+0000 [STG/0]      OUT Downloaded app package (524B)
        2017-06-27T16:38:35.38+0000 [STG/0]      OUT Staging...
        2017-06-27T16:38:35.46+0000 [STG/0]      OUT -------> Buildpack version 1.0.13
        2017-06-27T16:38:35.87+0000 [STG/0]      OUT Exit status 0
        2017-06-27T16:38:35.87+0000 [STG/0]      OUT Staging complete
        2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading droplet, build artifacts cache...
        2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading build artifacts cache...
        2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading droplet...
        2017-06-27T16:38:35.93+0000 [STG/0]      OUT Uploaded build artifacts cache (202B)
        2017-06-27T16:38:35.94+0000 [API/0]      OUT Creating droplet for app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
        2017-06-27T16:38:40.00+0000 [STG/0]      OUT Uploaded droplet (678B)
        2017-06-27T16:38:40.00+0000 [STG/0]      OUT Uploading complete
        2017-06-27T16:38:40.03+0000 [STG/0]      OUT Destroying container
        2017-06-27T16:38:40.37+0000 [CELL/0]     OUT Creating container
        2017-06-27T16:38:40.37+0000 [STG/0]      OUT Successfully destroyed container
        2017-06-27T16:38:40.79+0000 [CELL/0]     OUT Successfully created container
        2017-06-27T16:38:40.86+0000 [CELL/0]     OUT Starting health monitoring of container
        2017-06-27T16:38:41.21+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  WEBrick 1.3.1
        2017-06-27T16:38:41.21+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  ruby 2.3.3 (2016-11-21) [x86_64-linux]
        2017-06-27T16:38:41.22+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  WEBrick::HTTPServer#start: pid=6 port=8080
        2017-06-27T16:38:42.95+0000 [CELL/0]     OUT Container became healthy
        2017-06-27T16:38:51.13+0000 [RTR/1]      OUT CATS-2-APP-11a34b0f-988a-400c-6.cflab.ic.deere.com - [2017-06-27T16:38:51.128+0000] "GET /env HTTP/1.1" 200 0 1454 "-" "curl/7.38.0" "204.53.110.1:42226" "10.0.5.10:60810" x_forwarded_for:"204.53.110.1" x_forwarded_proto:"https" vcap_request_id:"e84c9913-1597-4845-7614-c7d07e80528c" response_time:0.007439526 app_id:"771951ae-0f2f-4543-99fa-a3cc66e07be2" app_index:"0"
        
    to match regular expression
        <string>: TASK.*LANG=en_US\.UTF-8

    /go/src/github.com/cloudfoundry/cf-acceptance-tests/apps/default_environment_variables.go:170
```
It appears from the test output that it does not wait very long (perhaps only 1-2 seconds) after the task is found to be in `SUCCEEDED` state before expecting the output to be in the logs. 

```
[2017-06-27 16:38:52.81 (UTC)]> cf tasks CATS-2-APP-11a34b0f-988a-400c-6 
Getting tasks for app CATS-2-APP-11a34b0f-988a-400c-6 in org CATS-2-ORG-c5422bbe-f07a-4ba1-5 / space CATS-2-SPACE-ab57098b-8701-4859-5 as CATS-USER-2-2017_06_27-15h35m04.78s...
OK

id   name      state       start time                      command
1    get-env   SUCCEEDED   Tue, 27 Jun 2017 16:38:51 UTC   env
```
vs the last check of the log at:
```
[2017-06-27 16:38:54.53 (UTC)]> cf logs CATS-2-APP-11a34b0f-988a-400c-6 --recent 
Connected, dumping recent logs for app CATS-2-APP-11a34b0f-988a-400c-6 in org CATS-2-ORG-c5422bbe-f07a-4ba1-5 / space CATS-2-SPACE-ab57098b-8701-4859-5 as CATS-USER-2-2017_06_27-15h35m04.78s...

2017-06-27T16:38:27.35+0000 [API/0]      OUT Created app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
2017-06-27T16:38:27.77+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"route"=>"583b3a7a-1942-4944-914b-fade1316bded", :verb=>"add", :relation=>"routes", :related_guid=>"583b3a7a-1942-4944-914b-fade1316bded"})
2017-06-27T16:38:33.89+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"diego"=>true})
2017-06-27T16:38:34.58+0000 [API/0]      OUT Creating build for app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
2017-06-27T16:38:34.70+0000 [API/0]      OUT Updated app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2 ({"state"=>"STARTED"})
2017-06-27T16:38:34.73+0000 [STG/0]      OUT Downloading binary_buildpack...
2017-06-27T16:38:34.74+0000 [STG/0]      OUT Downloaded binary_buildpack
2017-06-27T16:38:34.74+0000 [STG/0]      OUT Creating container
2017-06-27T16:38:35.34+0000 [STG/0]      OUT Successfully created container
2017-06-27T16:38:35.34+0000 [STG/0]      OUT Downloading app package...
2017-06-27T16:38:35.38+0000 [STG/0]      OUT Downloaded app package (524B)
2017-06-27T16:38:35.38+0000 [STG/0]      OUT Staging...
2017-06-27T16:38:35.46+0000 [STG/0]      OUT -------> Buildpack version 1.0.13
2017-06-27T16:38:35.87+0000 [STG/0]      OUT Exit status 0
2017-06-27T16:38:35.87+0000 [STG/0]      OUT Staging complete
2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading droplet, build artifacts cache...
2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading build artifacts cache...
2017-06-27T16:38:35.87+0000 [STG/0]      OUT Uploading droplet...
2017-06-27T16:38:35.93+0000 [STG/0]      OUT Uploaded build artifacts cache (202B)
2017-06-27T16:38:35.94+0000 [API/0]      OUT Creating droplet for app with guid 771951ae-0f2f-4543-99fa-a3cc66e07be2
2017-06-27T16:38:40.00+0000 [STG/0]      OUT Uploaded droplet (678B)
2017-06-27T16:38:40.00+0000 [STG/0]      OUT Uploading complete
2017-06-27T16:38:40.03+0000 [STG/0]      OUT Destroying container
2017-06-27T16:38:40.37+0000 [CELL/0]     OUT Creating container
2017-06-27T16:38:40.37+0000 [STG/0]      OUT Successfully destroyed container
2017-06-27T16:38:40.79+0000 [CELL/0]     OUT Successfully created container
2017-06-27T16:38:40.86+0000 [CELL/0]     OUT Starting health monitoring of container
2017-06-27T16:38:41.21+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  WEBrick 1.3.1
2017-06-27T16:38:41.21+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  ruby 2.3.3 (2016-11-21) [x86_64-linux]
2017-06-27T16:38:41.22+0000 [APP/PROC/WEB/0]ERR [2017-06-27 16:38:41] INFO  WEBrick::HTTPServer#start: pid=6 port=8080
2017-06-27T16:38:42.95+0000 [CELL/0]     OUT Container became healthy
2017-06-27T16:38:51.13+0000 [RTR/1]      OUT CATS-2-APP-11a34b0f-988a-400c-6.cflab.ic.deere.com - [2017-06-27T16:38:51.128+0000] "GET /env HTTP/1.1" 200 0 1454 "-" "curl/7.38.0" "204.53.110.1:42226" "10.0.5.10:60810" x_forwarded_for:"204.53.110.1" x_forwarded_proto:"https" vcap_request_id:"e84c9913-1597-4845-7614-c7d07e80528c" response_time:0.007439526 app_id:"771951ae-0f2f-4543-99fa-a3cc66e07be2" app_index:"0"
<this is where the TASK logs eventually would show up>
```

In our environment (potentially terrible, it is openstack-based...:yolo:) it seems to take 3-4s from after task is in `SUCCEEDED` state til the logging shows up... but it does show up.  I'm not sure if this means something is really slow in aggregating the task container logs, or whats going on, but I'm interested if we're the only ones having issues with this test.

### PR DESCRIPTION
**Pull request by bradylove**
Fixes #218

The test previously would only get recent logs once and assert that the environment variables are in the logs, however sometimes it can take a second or two longer for those logs to show up. This change will pull `logs --recent` until it finds one of the environment variables or hits the default timeout.

@enocom

### CODE REVIEW

**Comment by dsabeti** [comment]
Hey @bradylove @enocom. I think this is an improvement over what we already have, but it does look like you're counting on the fact (is it a fact?) that receiving the last line in the logs means that you've received all the other lines in the logs. 

Do I understand that correctly? Phrased differently, is there a reason why each regex match isn't part of an `Eventually` block?

**Comment by dsabeti** [comment]
cc @zrob @Gerg

**Comment by enocom** [comment]
@dsabeti Yes, you're correct. We are making that assumption, which probably means the window of spurious failure still exists, however small it may be.

**Comment by jaresty** [comment]
This looks like an improvement over what we've got, and doesn't look likely to cause any new failures.  Merging will monitor for a successful run before delivering the story.

**Pull request merged**
