### PR TITLE
Upgrade the noaa library

### PR DESCRIPTION
**Pull request by ljfranklin**
We did this originally because we thought we needed a newer version of
noaa to enable SOCKS5 https_proxy support. We don't think it fixed our
problem, but we did the work to bump the dependency anyways...

Signed-off-by: Chris Hendrix <chendrix@pivotal.io>

### CODE REVIEW

**Comment by ljfranklin** [comment]
I have no idea why the CLA bot is mad at me...

**Comment by ytulsiani** [comment]
Hey @chendrix, thank you for this PR!

We just need to publicize your membership to the CloudFoundry org. The instructions on how to do that are [here](https://help.github.com/articles/publicizing-or-hiding-organization-membership/). We will close this PR for now and open it once you do this.

Thanks!

**Comment by heyjcollins** [comment]
Hey @ljfranklin - did you try following the instructions and were you still unable to proceed?
If you did publicize your CF membership, I think you just need to click the reopen and comment button below and we'll be good to go.

**Comment by ljfranklin** [comment]
My memberships are all public, not sure what I could change ¯\_(ツ)_/¯

**Comment by ljfranklin** [comment]
nvm, we ended up not needing the bump. Just gonna close this out.

**Pull request closed without merging**
