### PR TITLE
PHP fixture reqires more memory for deployment

### PR DESCRIPTION
**Pull request by jtarchie**
[#103840940]
https://www.pivotaltracker.com/story/show/103840940

Signed-off-by: Amin Jams <aminjam.software@gmail.com>

### CODE REVIEW

**Comment by jtarchie** [comment]
@Amit-PivotalLabs we are upping the memory.

**Comment by Amit-PivotalLabs** [comment]
@jtarchie I thought you guys were going to investigate why this suddenly started happening, and only on your environment?  We've been very behind on community stuff, in particular your PR to improve log output when the buildpack test fails, apologies for that.  We will definitely fix that.

**Comment by Amit-PivotalLabs** [comment]
@jtarchie @aminjam any update on my above question?

**Comment by jtarchie** [comment]
@Amit-PivotalLabs we do appear to be the only ones to experience it. We've done everything we can to emulate, we think, the rest of the organization's CF AWS bosh-lite deployments.

* running CATs as a `bosh errand`
* recreating the box on every pipeline run

It still shows up, every once and a while. We still have no insight to how it fails. The app stages successfully, apache starts loading, and for 30 seconds FastCGI PHP does not start.

I've got an educated guess (hunch) that it is memory issue. I'd like to increase and see if it just disappears for ever.

**Comment by Amit-PivotalLabs** [comment]
After investigating this with @jtarchie, I believe this specific change is not necessary.  Closing this PR for now.

**Pull request closed without merging**
