### PR TITLE
Fix the example-cats-config

### PR DESCRIPTION
**Pull request by ameowlia**
### What is this change about?

Update the example config to add required property "credhub_secret".

### CODE REVIEW

**Comment by jamespollard8** [comment]
hey @ameowlia, could you please make sure you're properly associated with the commit?

**Review by jamespollard8 — APPROVED** [review]
These changes look good to me - thank you!

**Comment by ameowlia** [comment]
I fixed the commit and I closed+reopened in hopes that the EasyCLA would run again 🤔 

Yesterday I had this same problem [with this PR](https://github.com/cloudfoundry/cf-acceptance-tests/pull/452), but it seems to be fixed now. I wonder why not here.

**Comment by ameowlia** [comment]
I moved it from authored by george to authored by me and it seems to have fixed it. I wonder if everyone has to resign like I did yesterday?

**Pull request merged**
