### PR TITLE
Use CF CLI to create and delete service bindings

### PR DESCRIPTION
**Pull request by henryaj**
### What is this change about?
Update service binding tests to use the CF CLI instead of `cf curl`. This new test is designed to work with both the current wording and the updated wording introduced in https://github.com/cloudfoundry/cli/pull/1452.

https://www.pivotaltracker.com/story/show/159168130

### Please check all that apply for this PR:
- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [x] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?
- [ ] YES
- [x] N/A

### How many more (or fewer) seconds of runtime will this change introduce to CATs?
no change

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

@georgi-lozev

### CODE REVIEW

**Comment by georgi-lozev** [comment]
Keep in mind the minimum required version of the CLI in the environment where you're going to execute the tests is [v6.39.0](https://github.com/cloudfoundry/cli/releases/tag/v6.39.0).

**Comment by henryaj** [comment]
Ping @heyjcollins @ishustava - let us know if you need anything else from us on this. :)

**Comment by heyjcollins** [comment]
Hey @henryaj - if this requires v6.39.0 of the CLI, we're actually blocked from moving forward untill the CLI team can make an update to support another CAT that started failing. We're pinned to an earlier version 'till that's resolved. I can let them know you're blocked so up the anti.

**Comment by nmaslarski** [comment]
Thank you for the attention!
Yes, this does requires 6.39.0.
It's blocking only this PR, you can ping them if you like.
Thanks.

**Comment by henryaj** [comment]
Hi @heyjcollins - just wanted to ping you on this. Did the CLI team get round to making that fix?

**Comment by mattmcneeney** [comment]
[v6.40.0](https://github.com/cloudfoundry/cli/releases) is the latest release, so this should be good to go!

**Pull request merged**
