### PR TITLE
Add a test to ensure uaa/capi can emit metrics about system health

### PR DESCRIPTION
**Pull request by Benjamintf1**
- used to ensure component `statsd injector release` is working

Signed-off-by: Josh Russett <jrussett@vmware.com>

### What is this change about?

We want to run CATs to ensure the health/development of specifically the statsd injector. You can delete the statsd injector from the platform and no other tests fail, thusly we want to ensure increased coverage. Statsd injector is used to emit metrics about uaa and capi into loggregator. This helps us deprecate cfarlats

### What version of cf-deployment have you run this cf-acceptance-test change against?

latest

### Please check all that apply for this PR:
- [x] introduces a new test --- Are you sure everyone should be running this test? everyone has a uaa, it should be mostly equivilent to previous tests
- [ ] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?
- [x] YES
- [ ] N/A

### If you are introducing a new acceptance test, what is your rationale for including it CATs rather than your own acceptance test suite?

_CATs should validate common operator workflows._
operators like their metrics coming out of loggregator
_CATs is not a regression test suite._
_CATs is run by every component team to validate their releases before promotion._

### How should this change be described in cf-acceptance-tests release notes?
new test to validate that uaa and capi can emit metrics about themselves

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

less then 10 seconds

### What is the level of urgency for publishing this change?

- [x] **Urgent** - unblocks current or future work
- [ ] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
@cloudfoundry/runtime

### CODE REVIEW

**Comment by Benjamintf1** [comment]
hmm, i think we @ logging and metrics should maybe put more thought into this.

**Comment by heycait** [comment]
> hmm, i think we @ logging and metrics should maybe put more thought into this.

@Benjamintf1 is this ready to go in? Or is there still more here so we shouldn't merge?

**Comment by Benjamintf1** [comment]
@heycait I'm rethinking this. As much as I'd love to standardize our pipes around cats, I am unsure(starting to think it's a bad idea) to introduce more "non app dev"/"platform expirience" queries/tests into cats. But I'd be interested in your thoughts here if you wish.

**Comment by heycait** [comment]
Yea that makes sense not to add more to CATs. Also to note, we are just the current custodians of CATs so this question might be better answered by folks dealing with CF directly

**Pull request closed without merging**
