### PR TITLE
assets/nora: Doc on how to build

### PR DESCRIPTION
**Pull request by arjun024**
### What is this change about?

Add doc on how to build the nora app

### Please provide contextual information.

Nora is the dotnet app used to test CF on windows. A person should be able to make code changes and build the app easily to test different scenarios.

### What version of cf-deployment have you run this cf-acceptance-test change against?
No changes in app source code

### Please check all that apply for this PR:
- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [ ] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?
- [X] YES
- [ ] N/A

### Tag your pair, your PM, and/or team!
@yaelharel

### CODE REVIEW

**Comment by davewalter** [comment]
Hi @arjun024,

The team is concerned by the binary file changes included in this PR. Were they intentionally included? If so, can you please elaborate on their use?

Thanks,
Dave

**Comment by davewalter** [comment]
Hi @arjun024,

We have decided to remove the `assets/nora/bin` directory as we are concerned about the new binaries.

Regards,
Dave

**Comment by arjun024** [comment]
Hi @davewalter, they are required to build the app. The project file `/assets/nora/Nora/Nora.csproj` says they have to be copied from the `bin/`. These binaries already exist under `/assets/nora/Nora/NoraPublished/bin` and are copied from there. The one extra binary is a 0 byte file placed in the `bin/` for legacy reasons.

**Comment by davewalter** [comment]
Hi @arjun024,

Could you please open a new PR to continue this discussion? The team felt that it was strange that a PR to update the docs added binaries.

Thanks,
Dave

**Comment by arjun024** [comment]
Will do. Thank you @davewalter.

**Pull request merged**
