### PR TITLE
test app start events through cf-cli

### PR DESCRIPTION
**Pull request by zachgersh**
- no more parsing logs directly from the cc

There is a story in the capi backlog for dis.

Signed-off-by: Zachary Gershman <zgershman@pivotal.io>

### CODE REVIEW

**Comment by dsabeti** [comment]
@SocalNick @utako This PR seems good to me, but it's in the v3 suite and think that CAPI should weigh in before we merge. What are your thoughts on merging this in?

**Comment by SocalNick** [comment]
I believe this was discussed with CAPI before submission or shortly after. @utako @aashah can you let @dsabeti know when this is good to merge?

**Comment by zrob** [comment]
@zachgersh Unfortunately this changes the intention of the test.  The previous test was checking for AppUsageEvents across multiple processes, which is ensuring that each process can be properly billed.

The new implementation is testing AuditEvents. These are used as an audit trail.

I think it is important to continue ensuring that we generate the proper billing information.  Unfortunately there is not a cli friendly way that I'm aware of to list the usage information, which makes the whole page issue a problem still :(

**Comment by dsabeti** [comment]
In light of @zrob's comment, it sounds like we should close this PR. 

@zachgersh, any opposition to me closing this? Was this just a good citizen refactor, or is there a specific need not being met? In the latter case, could you submit a different PR?

**Comment by zachgersh** [comment]
@dsabeti I'd actually like to fix this - the test is flakey with the way it looks up events so I'd love to figure out a better way to do that. Maybe @zrob has an idea on how to do that.

**Comment by dsabeti** [comment]
@zachgersh Sure, seems reasonable to make tests less flaky.

Can you describe the failure mode of the flakiness? Maybe we can find another way to make the tests more reliable. Would it help to add something like retry logic to [LastPageUsageEvents](LastPageUsageEvents)?

**Comment by zrob** [comment]
I'd still like to see this resolved, I've opened an issue for the underlying problem, you can drop it in the capi backlog @dsabeti

**Comment by dsabeti** [comment]
@zrob I just transferred the story to the CAPI backlog

**Comment by zrob** [comment]
Closing in favor of https://github.com/cloudfoundry/cf-acceptance-tests/issues/184

**Pull request closed without merging**
