### PR TITLE
CI: Add GH actions workflow

### PR DESCRIPTION
**Pull request by ctlong**
### Are you submitting this PR against the [develop branch](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop)?

Yes

### What is this change about?

Add a GH actions workflow for CI purposes.

### Please provide contextual information.

None

### What version of cf-deployment have you run this cf-acceptance-test change against?

N/A

### Please check all that apply for this PR:

- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [ ] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?

- [ ] YES
- [x] N/A

### If you are introducing a new acceptance test, what is your rationale for including it CATs rather than your own acceptance test suite?

N/A

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

None

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

None

### CODE REVIEW

**Comment by ctlong** [comment]
Part of #1372

**Review by davewalter — APPROVED** [review]
Looks good. The only question I have is whether this workflow needs to run on a schedule in addition to when changes are made to the core branches?

**Comment by ctlong** [comment]
> Looks good. The only question I have is whether this workflow needs to run on a schedule in addition to when changes are made to the core branches?

It doesn't need to run on a schedule. I added the schedule out of habit, as many of the GH actions workflows I've written in the past contain jobs that may change over time (e.g. linting). These specific jobs should be consistent without code changes though, so I'll remove the schedule.

**Review by davewalter — APPROVED** [review]

**Comment by ctlong** [comment]
The revert commit above was accidental. I've deleted the branch now.

**Pull request merged**
