### PR TITLE
CATS: cease testing CAPI Experimental

### PR DESCRIPTION
**Pull request by cunnie**
### Are you submitting this PR against the [develop branch](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop)?

YES

### What is this change about?

CATS: cease testing CAPI Experimental

- CAPI Experimental consists of one test, route mappings (`/v3/route_mappings`)
- The route-mapping endpoint is deprecated and replaced with
  route-destinations (`/v3/routes/route_GUID/destinations`)
- The V3 tests have their own suite, specified by `include_v3`. In
  hindsight, this test should have been placed there.
- This commit will prevent CI failures when the route mappings endpoint
  is removed but users' CATS configuration specifies to test the
  route_mapping endpoint, that is,
  CAPI Experimental suite (i.e. `{"include_capi_experimental": true}`).
- We removed the tests, the directory containing the tests, and
  the corresponding imports of the test package.

### Please provide contextual information.

Relevant VAT tracker story: https://www.pivotaltracker.com/story/show/166239357
Relevant slack threads:
-https://cloudfoundry.slack.com/archives/C0FAEKGUQ/p1563814289004900

### What version of cf-deployment have you run this cf-acceptance-test change against?

Fairly recent version

### Please check all that apply for this PR:
- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [X] changes an existing test†
- [ ] requires an update to a CATs integration-config

† _(Existing CATS integration-configs will continue to work as-is, however the directive `"include_capi_experimental": true` will be a no-op)_

### Did you update the README as appropriate for this change?
- [X] YES
- [ ] N/A

We removed all references to CAPI Experimental tests from the README and from the sample JSON integration config.

### If you are introducing a new acceptance test, what is your rationale for including it CATs rather than your own acceptance test suite?

N/A

### How should this change be described in cf-acceptance-tests release notes?

No longer testing CAPI experimental features. New CAPI V3 features are tested under V3 test suite.

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

None (the test is not run by default; removing it will not reduce test duration).

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

/cc @Gerg @piyalibanerjee @ewrenn8 @tcdowney @selzoc

### CODE REVIEW

**Comment by selzoc** [comment]
@cunnie are there equivalent `destinations` tests in `baras` or `v3` `cats`?

**Comment by cunnie** [comment]
@selzoc : I don't know if there are equivalent tests, but that's a good question that came across my mind too. I've entered a tracker story https://www.pivotaltracker.com/story/show/167475997

**Comment by cunnie** [comment]
@selzoc We recently updated the `baras` to use V3 destinations when mapping/unmapping routes: https://github.com/cloudfoundry/capi-bara-tests/commit/a70d9d4c4e136a63f6f7aca5605f736f6d75d398

**Comment by cunnie** [comment]
Am closing & re-opening to force the re-validation of the CLAs.

**Pull request merged**
