### PR TITLE
Adjust regex for container metrics

### PR DESCRIPTION
**Pull request by philippthun**
Adjust regex that "extracts" container metrics from cf-cli output. Memory/disk might be shown as `0B` initially.

Output from a failed CATS run:
```
Regex did not find a match in contents 'Showing health and status for app [...]
[...]
     state     since                  cpu    memory       disk       logging        details
#0   running   2024-04-04T10:35:13Z   0.0%   0B of 256M   0B of 1G   0B/s of 0B/s   
'
```

### CODE REVIEW

**Comment by a-b** [comment]
Hey, @philippthun, I was wondering if you are using the Docker image to pull the CF CLI. Is that possible?

**Comment by a-b** [comment]
Can you please double-check the version of cf cli you're running with your tests? I suspect it is v7

**Comment by a-b** [comment]
We think this is caused by a recent bump of https://pkg.go.dev/code.cloudfoundry.org/bytefmt .

**Review by a-b — APPROVED** [review]
LGTM

**Comment by ctlong** [comment]
We are fairly confident that the issue is arising from a bytefmt bump in cf CLI 8.7.10 that picked up [this change](https://github.com/cloudfoundry/bytefmt/commit/854d396b647c90b5a45646f9dcc2c9cd08ea8d51). Accordingly, I'm going to look to merge this PR.

Thanks @philippthun !

**Review by ctlong — DISMISSED** [review]

**Review by ctlong — APPROVED** [review]

**Pull request merged**
