### PR TITLE
Add rlp tests

### PR DESCRIPTION
**Pull request by MasslessParticle**
### Are you submitting this PR against the [develop branch](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop)?

_All PR's to CATs should be submitted to develop and will be merged to master once they've passed acceptance._

### What is this change about?

This adds a CATS test for the RLP gateway functionality

### Please provide contextual information.

https://www.pivotaltracker.com/story/show/164224768

### What version of cf-deployment have you run this cf-acceptance-test change against?

7.6.0

### Please check all that apply for this PR:
- [x] introduces a new test --- Are you sure everyone should be running this test?
- [ ] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?
- [x] YES
- [ ] N/A

### If you are introducing a new acceptance test, what is your rationale for including it CATs rather than your own acceptance test suite?

_CATs should validate common operator workflows._
_CATs is not a regression test suite._
_CATs is run by every component team to validate their releases before promotion._

We've added a test to validate operator workflow that will replace the firehose

### How should this change be described in cf-acceptance-tests release notes?

Add v2 Logging test

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

44.725 seconds

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

@jtuchscherer @johncornish

### CODE REVIEW

**Comment by ab-pivot** [comment]
Hi @MasslessParticle,

We have some concerns about the number of vendored packages that this PR introduces. Is it possible to eliminate the dependency on `go-loggergator` to remove the vendored packages? We don't want to bloat the CATs repository if it can be avoided due to the adverse effect it would have on teams running the tests in CI.

Regards,
Alexander and @davewalter

**Comment by MasslessParticle** [comment]
@ab-pivot @davewalter 
https://cloudfoundry.slack.com/archives/C02HCCXV5/p1553008644081200

**Comment by cdutra** [comment]
Hi @MasslessParticle, we did some work to use `go mod` instead of `gvt`. This should improve the the vendoring of dependencies. Could you please update the PR or open a new one using the new `go mod`. Thanks

cc @davewalter

**Comment by MasslessParticle** [comment]
@cdutra We've moved the PR to go mod.

**Comment by cdutra** [comment]
@MasslessParticle It seems it's not vendoring your dependencies. Did you run both commands?
```
go mod tidy
go mod vendor
```

**Comment by MasslessParticle** [comment]
@cdutra @vitreuz 

Oops, sorry about that. We've vendored the dependencies

**Comment by davewalter** [comment]
@MasslessParticle It looks like there are some conflicts with your changes. Could you please resolve them?

Thanks,
Dave

**Comment by MasslessParticle** [comment]
@cdutra 

Thanks for the heads up. Lets try this

**Pull request merged**
