### PR TITLE
Migrate CATs to use v3 CAPI endpoints

### PR DESCRIPTION
**Pull request by sweinstein22**
### Are you submitting this PR against the develop branch?

Yes

### What is this change about?

These commits convert calls leveraging v2 Cloud Controller API endpoints to use the v3 CAPI endpoints, as part of VAT's work to deprecate v2 CAPI.

### Please provide contextual information.

- Slack conversation regarding making these changes and PR-ing them in as a collective: https://pivotal.slack.com/archives/C3LUD2L04/p1595277418062500
- VAT Tracker epic for these conversions: https://www.pivotaltracker.com/epic/show/4611384

### What version of cf-deployment have you run this cf-acceptance-test change against?

v13.19.0

### Please check all that apply for this PR:
- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [x] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?
- [ ] YES
- [x] N/A

### If you are introducing a new acceptance test, what is your rationale for including it CATs rather than your own acceptance test suite?

N/A

### How should this change be described in cf-acceptance-tests release notes?

Migrate endpoints leveraging v2 Cloud Controller API endpoints to v3.

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

It should be minimal, however we are aware that some endpoints seem to be slower in v3. We are working on making improvements to performance, and if any tests seem to run really slowly we would love to hear that feedback from you all!

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

@tstannard @MerricdeLauney @reid47 @selzoc @monamohebbi @Gerg

### CODE REVIEW

**Comment by ericpromislow** [comment]
Hi @sweinstein22,  

Could you ensure that the following teammates all set up their CLAs?

@monamohebbi @tstannard @MerricdeLauney 

Thanks,
Eric and @jamespollard8

**Comment by sweinstein22** [comment]
Hi @ericpromislow , 

Sorry for the delay, we're working on it - it seems like since the VMware merge getting EasyCLA stuff sorted has gotten more complicated. We've had some issues with people getting locked out of their accounts so it might take a bit but we'll get it done as soon as we can!

**Comment by jamespollard8** [comment]
> Sorry for the delay, we're working on it - it seems like since the VMware merge getting EasyCLA stuff sorted has gotten more complicated. We've had some issues with people getting locked out of their accounts so it might take a bit but we'll get it done as soon as we can!

Oh yeah, no rush on our end. I'm assuming (hoping) your CLA situations will get resolved faster than we'll be able to review this

**Comment by reid47** [comment]
@jamespollard8 @ericpromislow do you know how to refresh the CLA bot? We believe Teal has now signed the CLA (several times! in an attempt to get the bot to refresh), but we're still blocked.

**Comment by davewalter** [comment]
Hi @sweinstein22 et al, We discussed this at techro and were actually wondering whether a lot of these tests are duplicates now that the V3 API is being tested indirectly through calls from the CLI. Our assumption is that y'all are testing the entire API through your own integration tests (baras?), so we were hoping that y'all could review the list of API calls that CATs is currently testing directly and eliminate anything that you don't expect a reasonably large percentage of CF users to make use of. For more context, please see some notes from a recent discussion we had about [the purpose of CATs](https://docs.google.com/document/d/1HNfpiH_APjKqO6zbBD7doD0bP-yG-ww3waW_JdpFYx0/edit), especially in relation to running it against cf-for-k8s.

**Comment by sweinstein22** [comment]
Hi @davewalter , 

We actually don't test the entire API through our own integration tests, and rely on CATs for some of that coverage. A lot of the API calls are also in helpers/used as setup for other tests. For example we've made changes to the volume services suite, but we don't actually own the volume services functionality. Are there particular tests you all feel are ill-suited to CATs?

**Comment by ericpromislow** [comment]
I found the problem I had with the CLI bot was that I was using an email alias on github. I changed my primary email address to my "raw" suse email address, reapplied for a CLA, and that fixed my issue.  Also, Heather as the linux foundation was also responsive, but I forget how I managed to get help from them.

________________________________

**Comment by ericpromislow** [comment]
@reneighbor and I have decided to move forward accepting this PR (we haven't checked for merge conflicts and errors yet) since it doesn't add to the CATs footprint, it just migrates the endpoint tests from v2 to v3).  Pruning CATs should be done by another story.

**Review by ericpromislow — COMMENTED** [review]
We'll probably make these changes post-merge (if we can).

**Comment by ericpromislow** [comment]
Hi, our policy is to request any PRs that have more than 3 commits to squash the commits down to 1 and then resubmit the PR.

While you're at it, please act on the items in the [review](https://github.com/cloudfoundry/cf-acceptance-tests/pull/435#pullrequestreview-493773038) . It looks like the commented-out code can be deleted (assuming its test continued to pass).

We understand the CLA issue because one of us (Eric) has been there recently.

- Eric and @reneighbor

**Pull request closed without merging**
