### PR TITLE
Fix CATs to allow it to run in more configuration

### PR DESCRIPTION
**Pull request by jvshahid**
This PR consists of three commits that can be reviewed in isolation.  The commit message of each change explains the intention behind the change.

### What is this change about?

We intend to run CATs in our managed environment on AWS.

### Please provide contextual information.

https://vmware.slack.com/messages/C3LUD2L04/p1602100943001300

### What version of cf-deployment have you run this cf-acceptance-test change against?

CATs 5.11.0

### Please check all that apply for this PR:

- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [X] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?

- [ ] YES
- [X] N/A

### How should this change be described in cf-acceptance-tests release notes?

I think the three commit messages are good candidates since they are descriptive and brief.  I will include them below:

```
Use https syslog drain URL instead of syslog-tls.
Use Config.Protocol() instead of hard coding the protocol.
Fix the test to reflect the original intention.
```

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

This change will make CATs faster since the Syslog test was simplified and doesn't wait or parse the Syslog listener logs anymore.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

@Logiraptor @houlistonm

### CODE REVIEW

**Comment by davewalter** [comment]
Hi @jvshahid,

We are seeing a [failure in our CATs CI pipeline](https://release-integration.ci.cf-app.com/teams/main/pipelines/cats/jobs/run-cats/builds/249) with these changes. The syslog drains test (`apps/syslog_drain.go:98`) is consistently failing to validate that the logs contain the appropriate random message from the app that is supposed to be logging output. We have manually verified that this is related to the change to the commit to "Use https syslog drain URL instead of syslog-tls". Our pipeline is using a toolsmiths' pooled environment running the latest release of cf-deployment on GCP. Can you think of any reason why this should be failing?

Regards,
Dave

**Comment by jvshahid** [comment]
I'm sorry about that. I'm away from a computer at the moment but I could
take a look tomorrow morning.

**Comment by jvshahid** [comment]
To answer your question, it looks like the https load balancer to the
gorouter is unreachable from inside the diego containers. I'm not sure why
though. You could check the loggr-syslog-agent logs for more information.
It could be a security group issue or something with the infrastructure
firewall rules.

**Comment by davewalter** [comment]
Thanks @jvshahid. We'll take another look at it on Monday.

**Comment by davewalter** [comment]
Hi @jvshahid,

To get CI green, we have decided to revert 3fa457a886cadc367ffdaa0f2ceb2ec9a96e0700 as that is the change that is causing problems. If it is a change you still want to incorporate into CATs, it would be great if you could open a new PR and work with the networking folks to get this working. We're also available to help with specifics around our CI environments.

Regards,
Dave and @jamespollard8

**Pull request merged**
