### PR TITLE
Update docker test to reflect new env var behavior

### PR DESCRIPTION
**Pull request by jenspinney**
* Previously, $HOME would also be "app" and $TMPDIR would always be "app/tmp"
* With this change, if either of these variables were set with 'cf set-env', we use that value for the variable. Otherwise, we use the value of the variable defined in the Dockerfile, if set. Otherwise, $HOME will be set to the system default (from /etc/passwd) and $TMPDIR will remain unset.

* [X] I have viewed signed and have submitted the Contributor License Agreement

* [X] I have made this pull request to the `master` branch

* [X] I have successfully run these tests against bosh-lite 

[#122608871]

Paired with @caod123

### CODE REVIEW

**Comment by APShirley** [comment]
Thanks @jenspinney looks good, merging.

**Comment by RochesterinNYC** [comment]
@jenspinney @APShirley are there any configuration changes to CF or Diego required to make these tests pass? Our CATs is now failing on these two tests.

**Comment by jenspinney** [comment]
@RochesterinNYC Are you using the latest release of Diego? This should work on v0.1479.0 of Diego and higher.

**Comment by RochesterinNYC** [comment]
We're running `v0.1476.0` so that's probably why. Thanks.

**Pull request merged**
