### PR TITLE
Check for errors while slurping

### PR DESCRIPTION
**Pull request by fraenkel**
The reformat was due to moving the test under the correct context.
Check for errors from the firehose.

[##116437533]

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Looks like you have some extra whitespace.

**Comment by fraenkel** [comment]
That is github being github. It's gofmt'd already.

**Comment by Amit-PivotalLabs** [comment]
@wfernandes moving the story for this PR (udpate to loggregator test in CATS) to your icebox.  Btw, I can't find Jim Campbell's github handle easily.

**Comment by wfernandes** [comment]
@Jim-Campbell

**Comment by wfernandes** [comment]
@Amit-PivotalLabs Thanks. We'll prioritize it soon.

**Pull request merged**
