### PR TITLE
Remove empty app name message when running tests.

### PR DESCRIPTION
**Pull request by davewalter**
It makes the test output extremely verbose when running with the --succinct ginkgo flag. For example, when running just the v3 test group, the output currently looks like this:
```
+ ginkgo --failFast --succinct --nodes=4
[1482431888] CATS - 133/135 specs - 4 nodes 
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

SSSS
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

SS
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

SSSSSSSSSS
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

SS
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
• [SLOW TEST:20.974 seconds]
[v3] package features with a valid package can copy package bits to another app and download the package 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/package.go:88
------------------------------
• [SLOW TEST:27.008 seconds]
[v3] buildpack Stages with a user specified admin buildpack 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/buildpacks.go:67
------------------------------
• [SLOW TEST:30.331 seconds]
[v3] route_mapping Route mapping lifecycle creates a route mapping on a specified port 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/route_mapping.go:95
------------------------------
App name was set to ""; skipping app report.

SS
------------------------------
• [SLOW TEST:33.881 seconds]
[v3] package features when the package contains files in unwriteable directories can still stage the package 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/package.go:104
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

SSS
------------------------------
• [SLOW TEST:46.645 seconds]
[v3] process terminating an instance /v3/apps/:guid/processes/:type/instances/:index restarts the instance 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/process.go:105
------------------------------
• [SLOW TEST:29.991 seconds]
[v3] v3 tasks tasks lifecycle can successfully create and run a task 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/task.go:97
------------------------------
• [SLOW TEST:61.837 seconds]
[v3] buildpack uses buildpack cache for staging 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/buildpacks.go:108
------------------------------
• [SLOW TEST:15.684 seconds]
[v3] v3 tasks When canceling a task should show task is in FAILED state 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/task.go:131
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

SSSSSSSS
------------------------------
• [SLOW TEST:29.948 seconds]
[v3] droplet features copying a droplet can copy a droplet 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/droplet.go:85
------------------------------
• [SLOW TEST:61.395 seconds]
[v3] process terminating an instance /v3/processes/:guid/instances/:index restarts the instance 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/process.go:136
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

SSSPPS
------------------------------
• [SLOW TEST:19.424 seconds]
[v3] droplet features copying a droplet creates an audit.app.droplet.create event for the copied droplet 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/droplet.go:148
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

SS
------------------------------
App name was set to ""; skipping app report.

S
------------------------------
• [SLOW TEST:30.606 seconds]
[v3] v3 buildpack app lifecycle with a ruby_buildpack can run apps with processes from the Procfile 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/app_lifecycle.go:100
------------------------------
• [SLOW TEST:34.237 seconds]
[v3] v3 buildpack app lifecycle with a java_buildpack can run spring apps 
/tmp/build/f9b4e60d/go/src/github.com/cloudfoundry/cf-acceptance-tests/v3/app_lifecycle.go:146
------------------------------
App name was set to ""; skipping app report.
App name was set to ""; skipping app report.

S
------------------------------
App name was set to ""; skipping app report.

SSSSSSSSSSSSSSSSSSSS SUCCESS! 4m28.556438498s 

Ginkgo ran 1 suite in 4m54.037483978s
Test Suite Passed
```

### CODE REVIEW

**Comment by JesseTAlford** [comment]
Thanks for the pull request, Dave.

I put that message in. I'd like to see the output it's inflicting removed, but it's also telling me something: app reports are getting run far, far too frequently. I need to think about how to fix that a bit before I remove the pain of it.

I think I would rather use [this](https://github.com/onsi/ginkgo/blob/master/ginkgo_dsl.go#L141) to fix the problem than remove the empty-app-report warning, which has other debug utility, especially during development/shake-down of new tests.

**Comment by davewalter** [comment]
That's totally reasonable. Are you thinking something as simple as wrapping the `fmt.Println` like this? 
```
testDesc := CurrentGinkgoTestDescription()
if testDesc.Failed {
  fmt.Println("App name was set to \"\"; skipping app report.")
}
```

**Comment by JesseTAlford** [comment]
We'd probably actually prefer to wrap every after_each call in a conditional, so the app report can still be run unconditionally if desired, and so we don't have to pass in test state just to check if it's passing within the function.

We've merged this for now, because we want to relieve you of pain and fixing this right isn't top-of-backlog priority-level right now. We intend to come back and re-enable this message and change our calls in the after_each to be conditional.

We have a story [here](https://www.pivotaltracker.com/story/show/136970301) to change our calls. I hope we get to it/it happens outside our backlog soon, because I think it will also make cats baseline faster by potentially hundreds of fewer calls to the API.

We have a story [here](https://www.pivotaltracker.com/story/show/136970283) to restore the useful error message once that's done.

Thanks again for bringing this to our attention, @davewalter.

**Comment by davewalter** [comment]
Thanks @JesseTAlford / @jaresty. I am definitely looking forward to faster CATs in future!

**Pull request merged**
